#!/usr/bin/env bash
# this is a script to copy a file from client to remote server 
if [ "$#" -lt 4 ] ; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"

else
    scp -o "$1" "$3@$2" "$HOME/$4"
fi

